version: '3'

services: 
    max:
        build: https://github.com/IBM/MAX-Text-Summarizer.git
        ports:
            - "5000"
        restart: always

    flask:
        depends_on: 
            - max
        build: ./flask
        ports: 
            - "5000:5000"
        restart: always
