version: '3'

services: 
    max:
        build: ./MAX-Text-Summarizer
        restart: always

    flask:
        depends_on: 
            - max
        build: ./flask
        ports: 
            - "5000:5000"
        restart: always
